repos:
  - repo: local
    hooks:
      - id: run-formatter
        name: run node format
        language: node
        entry: npm run format
        exclude: '(.prettierignore|.eslintignore)'
  - repo: local
    hooks:
      - id: run-lint
        name: run node lint
        language: node
        entry: npm run lint
        exclude: '(.prettierignore|.eslintignore)'
